# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
       # in_memory:
        #    memory: ~
        our_db_provider:
            entity:
                class: AppBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
      #  dev:
          #   pattern: ^/(_(profiler|wdt)|css|images|js)/
          #   security: false #>

        # main:
           #  anonymous: ~
             main:
                form_login:
                    provider: our_db_provider
                    login_path: login
                    check_path: login
                    default_target_path: Accueil

                guard:
                    authenticators:
                    - app.token_authenticator
                remember_me:
                    secret: '%secret%'
                    lifetime: 604800 # 1 week in seconds
                    path: /
                    domain:   ~
                    user_provider: our_db_provider

                anonymous: true
                logout: ~



            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/config, roles: ROLE_ADMIN }
