category:
    path:     /
    defaults: { _controller: "AppBundle:Category:index" }

category_ajax:
    path:     /ajaxliste
    defaults: { _controller: "AppBundle:Category:ajaxliste" }
    requirements: { _method: post }

category_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Category:show" }

category_new:
    path:     /new
    defaults: { _controller: "AppBundle:Category:new" }

category_create:
    path:     /create
    defaults: { _controller: "AppBundle:Category:create" }
    requirements: { _method: post }

category_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Category:edit" }

category_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Category:update" }
    requirements: { _method: post|put }

category_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Category:delete" }
    requirements: { _method: post|delete }

category_remove:
    path:     /remove
    defaults: { _controller: "AppBundle:Category:remove" }
    requirements: { _method: post|delete }
