service:
    path:     /
    defaults: { _controller: "AppBundle:Service:index" }

service_ajax:
    path:     /ajaxliste
    defaults: { _controller: "AppBundle:Service:ajaxliste" }
    requirements: { _method: post }

service_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Service:show" }

service_new:
    path:     /new
    defaults: { _controller: "AppBundle:Service:new" }

service_create:
    path:     /create
    defaults: { _controller: "AppBundle:Service:create" }
    requirements: { _method: post }

service_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Service:edit" }

service_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Service:update" }
    requirements: { _method: post|put }

service_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Service:delete" }
    requirements: { _method: post|delete }

service_remove:
    path:     /remove
    defaults: { _controller: "AppBundle:Service:remove" }
    requirements: { _method: post|delete }
